In [1]:
#Import pandas & datetime packages
import pandas as pd
import datetime as dt

#Display all rows of data
pd.set_option('display.max_rows', None)

In [8]:
#Load CSV and convert to DataFrame
shoe_sales=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Marketing:Sales/Shoe Sales/Original CSVs/sales_transactions.csv')
shoe_sales.head(50)

,transaction_id,order_datetime,store_id,customer_id,customer_name,customer_email,customer_phone,customer_state,product_id,product_name,...,category,gender,color,size,quantity,unit_price,discount_pct,payment_method,order_status,channel
0,TXN104355,10-09-24,ST032,C44543,Mr. Larry Mcclure PhD,mr..larry.mcclure.phd@outlook.com,NaN,CA,P0048,Skechers Basketball Retro 4,...,Basketball,Child,NaN,11.0,1,131.27,25%,DEBIT,Completed,In-Store
1,TXN102187,12/10/2024,ST013,C26663,Sara Gordon,sara.gordon@aol.com,029-254-6862,MN,P0063,Adidas Casual Classic Leather,...,CASUAL,UNISEX,Blue,US 8,1,164.90,0.3,Debit Card,Completed,INSTORE
2,TXN103649,"November 17, 2025",ST008,C39850,Jessica Simmons,jessica.simmons@gmail.com,955.356.0331,GA,P0247,ASICS Lifestyle Disruptor II,...,lifestyle,Men's,Brown,US11,4,143.30,15%,GC,Completed,PHONE
3,TXN104559,"June 20, 2023",ST009,C24533,Sean Lewis,sean.lewis@hotmail.com,2151734660,NaN,P0215,Skechers Sandals Chuck 70,...,Sandals,UNISEX,Black,US8,2,$105.56,0.1,cash,Completed,In-Store
4,TXN103935,01/07/2025,ST013,C11482,Carrie Fernandez,carrie.fernandez@gmail.com,+14760882309,Georgia,P0283,Reebok SK8-Hi,...,lifestyle,UNISEX,Black/White,7,2,$167.56,0%,DEBIT,Completed,instore
5,TXN101690,"March 23, 2024",ST018,C28101,Danielle Cook,danielle.cook@gmail.com,NaN,TN,P0299,Adidas Stan Smith Lifestyle,...,LIFESTYLE,UNISEX,Multicolor,13 US,1,58.09,0.25,credit card,Completed,ONLINE
6,TXN103592,"January 15, 2024",ST011,C85941,Lance Harris,lance.harris@gmail.com,(870) 929-5162,TN,P0293,Puma Lifestyle 574,...,Lifestyle,kids,Brown,13.0,1,$140.88,0,PAYPAL,Completed,Phone Order
7,TXN107022,05/02/2025,ST023,C52016,Dustin Mitchell,dustin.mitchell@yahoo.com,(579) 672-4610,co,P0242,Converse D'Lites,...,skate,Unisex,Brown,US8,1,$69.99,0,Credit Card,Completed,online
8,TXN109011,11-Aug-2024,ST016,C14586,Thomas Atkins,thomas.atkins@hotmail.com,628-222-5018,NJ,P0167,Fila RS-X,...,skate,Men,Brown,US6,4,$50.94,0%,Debit,Completed,phone order
9,TXN103765,00/00/0000,ST012,C52813,Samantha Hernandez MD,samantha.hernandez.md@hotmail.com,(511) 788-2805,FL,P0214,New Balance Boots Curry Flow,...,Boots,W,Red,7.5,1,72.54,0%,Gift-Card,COMPLETE,Web
10,TXN102404,05/25/2024,ST012,C89477,Natalie Hoffman,natalie.hoffman@outlook.com,6665800439,WA,P0081,Vans Sandals Disruptor II,...,sandals,womens,Multicolor,Size 9.5,3,$118.38,0%,gift card,Completed,instore
11,TXN107574,"April 05, 2025",ST034,C77357,Rita Waller,rita.waller@gmail.com,(103) 930-8705,PA,P0130,New Balance Sandals 990v5,...,Sandals,Child,Beige,11,3,-100.93,0.25,CREDIT CARD,Completed,Web
12,TXN100777,19/02/2023,ST028,C52027,Kayla Bennett,kayla.bennett@yahoo.com,NaN,NJ,P0108,Under Armour Club C,...,sandals,Men,Brown,Size 8.5,1,$147.64,15%,Gift-Card,Completed,Online
13,TXN110696,23-Mar-2023,ST007,C75226,Susan Williams,susan.williams@hotmail.com,6740718533,NaN,P0156,Vans Lifestyle Zoom Pegasus,...,Lifestyle,UNISEX,Triple Black,Size 9,4,145.71,0,Cash,Completed,WEB
14,TXN101177,09/23/2025,ST023,C57734,Joseph Waters,joseph.waters@hotmail.com,1752047700,CA,P0104,Reebok Sandals D'Lites,...,Sandals,Women's,White,US 12,1,$-206.29,0,Apple Pay,Completed,PHONE
15,TXN102429,23-Oct-2025,ST034,C55026,Katherine Olson,NaN,660.323.7014,NaN,P0193,ASICS Basketball Disruptor II,...,BASKETBALL,Men,Green,US10.5,1,83.79,0,DEBIT,Completed,Phone Order
16,TXN101530,13/09/2025,ST022,C15060,Alexis Barker,alexis.barker@hotmail.com,+14916093659,NY,P0283,Reebok SK8-Hi,...,Lifestyle,UNISEX,Black/White,US10.5,-1,$-167.56,10%,APPLE PAY,Completed,Online
17,TXN107018,09/19/2023,ST003,C89195,Jason Munoz,jason.munoz@aol.com,0411678815,WA,P0032,Puma Retro 4,...,Cross-Training,Child,Triple Black,11,1,130.96,10%,cash,Completed,INSTORE
18,TXN110329,30-Apr-2023,ST012,C78835,Jerry Williams,jerry.williams@hotmail.com,640.703.0880,Tennessee,P0006,Converse D'Lites Training,...,Cross-Training,WOMENS,Black,US13,1,198.03,0.1,CREDIT CARD,Completed,Phone Order
19,TXN108854,11-24-22,ST014,C43767,Ashley White,ashley.white@gmail.com,2059438976,PA,P0228,ASICS 990v5 Basketball,...,BASKETBALL,unisex,Orange,10.5,1,NaN,0.3,APPLE PAY,Completed,phone order
20,TXN103500,01-25-22,ST003,C32792,Steven Gordon,steven.gordon@gmail.com,NaN,MN,P0072,Reebok 990v5,...,sandals,Men's,Black,13 US,4,219.97,0.25,PAYPAL,Completed,in-store
21,TXN103046,12-18-24,ST016,C20698,Edward Cruz,edward.cruz@hotmail.com,5545012221,TX,P0263,Under Armour Casual Chuck 70,...,Casual,Youth,Red,Size 7.5,2,$191.65,0.15,apple pay,Completed,online
22,TXN101803,27-Aug-2024,ST010,C10419,Lisa Lopez,lisa.lopez@outlook.com,4633891562,Georgia,P0155,Reebok 574 Basketball,...,BASKETBALL,Women's,White,8,1,199.70,0,Debit,Completed,instore
23,TXN102718,09/12/2024,ST036,C54059,Desiree Fox,desiree.fox@yahoo.com,+14899300519,NY,P0033,Nike 990v5,...,BOOTS,kids,Orange,US11,2,47.93,0.2,PAYPAL,Completed,Online
24,TXN106226,"November 20, 2024",ST034,C62598,William Dickson DDS,william.dickson.dds@aol.com,3891918740,Florida,P0236,Nike Running Old Skool,...,Running,KIDS,Navy,8.5,3,$132.76,0%,Apple Pay,Completed,Web
25,TXN110682,2023-03-26,ST014,C82973,Julia Jones,julia.jones@aol.com,(809) 010-1461,IL,P0290,ASICS Boots RS-X,...,boots,WOMENS,Navy,12 US,2,122.73,20%,gift card,Completed,phone order
26,TXN104325,21/08/2024,ST003,C29686,Brian Payne,NaN,791-944-5576,TX,P0188,Reebok D'Lites,...,lifestyle,mens,White,US 8,2,129.52,0%,GC,Completed,online
27,TXN103406,2024-07-02,ST024,C17985,Angela Caldwell,angela.caldwell@hotmail.com,(200) 761-5042,GA,P0225,Fila Classic Leather Sandals,...,sandals,MENS,Brown,10,4,$203.04,0.2,Gift Card,Completed,in-store
28,TXN110082,09/12/2023,ST006,C27705,Kenneth Huff,kenneth.huff at hotmail.com,405.391.0371,NY,P0205,Nike Gel-Kayano,...,Sandals,Women,Brown,Size 7,4,$105.49,0.1,DEBIT,Completed,instore
29,TXN103145,23/04/2023,ST015,C10143,Terri Valdez,terri.valdez@gmail.com,+14441076926,NY,P0349,Fila Sandals 574,...,SANDALS,kids,Red,11,1,70.46,0%,Cash,Completed,phone order
30,TXN100982,"November 05, 2022",ST004,C28596,Rebekah Ramirez,rebekah.ramirez@aol.com,(843) 965-6887,MN,P0208,Jordan Curry Flow Casual,...,Casual,M,Navy,US 10.5,2,144.88,15%,CREDIT CARD,Completed,in-store
31,TXN104401,06-Nov-2024,ST002,C35969,Krista Crane,krista.crane@aol.com,NaN,ca,P0240,Converse RS-X Skate,...,Skate,M,Beige,US10,4,170.86,30%,Pay Pal,Completed,ONLINE
32,TXN100506,2023-02-10,ST025,C60710,Leonard Morales,NaN,NaN,PA,P0196,Converse Disruptor II Casual,...,Casual,mens,Blue,8 US,3,$66.35,0,GC,Completed,ONLINE
33,TXN101836,24-May-2024,ST030,C26947,Steven Underwood,steven.underwood@yahoo.com,252-423-5256,MI,P0269,Converse RS-X,...,BASKETBALL,W,Navy,US9,3,123.96,25%,APPLE PAY,Completed,phone order
34,TXN104467,04-Mar-2022,ST023,C85891,Jessica Jones,jessica.jones@outlook.com,(443) 053-4475,MN,P0286,ASICS Boots Chuck 70,...,boots,Women,Red,9 US,1,$45.67,0.3,Cash,Completed,Phone
35,TXN103734,04-Dec-2024,ST019,C37149,Stephanie Bender,NaN,516-994-9708,GA,P0227,Puma Basketball D'Lites,...,basketball,womens,Black,US 6,3,115.56,0%,APPLE PAY,Completed,Online
36,TXN109576,09-18-25,ST005,C63559,Kurt Vasquez,kurt.vasquez at yahoo.com,087.106.2359,PA,P0176,Converse Running Stan Smith,...,running,Kids,Grey,US7,1,$103.29,0,CREDIT CARD,Completed,in-store
37,TXN108279,30-Dec-2025,ST036,C36484,Tammy Estrada,tammy.estrada@yahoo.com,(162) 585-1502,ma,P0138,Reebok Zoom Pegasus,...,Skate,MENS,Triple Black,11.0,2,$201.79,0%,Gift-Card,Completed,PHONE
38,TXN101536,10/05/2023,ST001,C23809,Nicholas Shaw,NaN,NaN,tx,P0297,Reebok Skate Club C,...,SKATE,Men's,Red,Size 9.5,1,150.81,0,Credit Card,Completed,in-store
39,TXN109373,"May 18, 2023",ST022,C11785,Laura Rodriguez,laura.rodriguez@gmail.com,(910) 292-9501,TN,P0004,Under Armour Cloudfoam Skate,...,skate,W,Orange,8 US,1,67.50,20%,Gift-Card,Completed,ONLINE
40,TXN100145,04-Dec-2025,ST013,C20357,Daniel Bright,daniel.bright@outlook.com,226.916.6978,PA,P0058,Adidas Casual Zoom Pegasus,...,Casual,UNISEX,Beige,Size 12,1,$160.15,30%,Cash,Completed,instore
41,TXN105947,"April 28, 2023",ST021,C70806,Crystal Montoya,crystal.montoya@outlook.com,(300) 716-9500,NaN,P0297,Reebok Skate Club C,...,skate,Men,Red,7.5.0,1,$150.81,10%,Debit Card,Completed,phone order
42,TXN104600,11/21/2023,ST006,C44253,Sara Castro,sara.castro@yahoo.com,652-057-5639,NY,P0108,Under Armour Club C,...,SANDALS,Men's,Brown,US8.5,1,147.64,0.25,Gift Card,Completed,PHONE
43,TXN107547,02/20/2025,ST035,C94823,Micheal Perry,micheal.perry@yahoo.com,NaN,NJ,P0090,Under Armour Retro 4,...,LIFESTYLE,Unisex,Multicolor,9.5.0,1,$88.75,0.3,Debit,Completed,In Store
44,TXN107356,07/31/2022,ST006,C82867,Tommy Potter,tommy.potter@outlook.com,9854506935,TX,P0060,ASICS Sandals Chuck 70,...,SANDALS,Child,Brown,7.0,1,NaN,0.1,cash,Completed,Phone
45,TXN108563,05/22/2024,ST020,C11770,Emily Palmer,NaN,(132) 796-8559,TX,P0129,Adidas Sandals RS-X,...,Sandals,WOMENS,Black,US8.5,2,$113.79,0,Apple Pay,Completed,WEB
46,TXN110469,08/15/2022,ST028,C75143,Nicole Robinson,nicole.robinson@yahoo.com,(202) 204-1064,pa,P0233,Converse Gel-Kayano,...,BASKETBALL,Kids,Beige,US 8,2,$64.00,0%,cash,Completed,online
47,TXN100056,2025-11-10,ST032,C20271,Jennifer Hampton,jennifer.hampton@outlook.com,NaN,NV,P0154,Fila D'Lites Boots,...,BOOTS,W,White,10.5 US,1,48.15,15%,apple pay,Completed,Phone Order
48,TXN103981,NaN,ST006,C47337,Autumn Harris,autumn.harris@hotmail.com,(725) 978-3367,NJ,P0168,Vans Stan Smith Basketball,...,Basketball,Unisex,Brown,12 US,2,$53.22,0.25,Credit,EXCHANGE,Phone
49,TXN107040,12-Dec-2025,ST011,C71739,Vanessa Booth,vanessa.booth@hotmail.com,574-865-9775,IL,P0301,Reebok Retro 4 Skate,...,skate,mens,Triple Black,US7.5,1,203.42,0.25,gift card,Completed,INSTORE

In [20]:
#Clean date column to ensure all values are of consistent formatting
shoe_sales['order_datetime']=pd.to_datetime(shoe_sales['order_datetime'],errors='coerce')
shoe_sales['order_datetime'].value_counts().head(50)

2023-09-09    19
2022-02-23    17
2025-04-28    16
2024-10-25    16
2025-11-23    16
2022-07-25    16
2022-01-13    16
2022-08-01    15
2022-11-02    15
2025-01-12    15
2024-06-28    15
2022-12-27    15
2023-12-02    15
2025-10-12    15
2022-01-10    15
2025-10-04    15
2022-01-09    15
2023-11-26    14
2025-08-11    14
2024-07-29    14
2023-11-20    14
2025-05-16    14
2022-08-19    14
2022-02-10    14
2025-04-26    14
2023-01-14    14
2025-10-22    14
2025-10-18    13
2024-03-30    13
2025-05-05    13
2022-12-16    13
2025-09-27    13
2024-01-15    13
2024-08-03    13
2024-05-31    13
2024-11-21    13
2024-04-27    13
2025-02-20    13
2024-05-15    13
2025-03-04    13
2023-10-03    13
2022-03-21    13
2022-08-26    13
2023-12-05    13
2024-04-10    13
2023-01-12    12
2025-07-29    12
2022-02-11    12
2022-08-16    12
2024-04-09    12
Name: order_datetime, dtype: int64

In [21]:
shoe_sales['category'].value_counts()

#Clean category column to ensure consistent text formatting
shoe_sales['category']=shoe_sales['category'].str.title()
shoe_sales['category'].value_counts()

#Replace typos/abbreviations where appropriate
shoe_sales['category']=shoe_sales['category'].replace({'Bball':'Basketball','Runing':'Running'})
shoe_sales['category'].value_counts()

Casual            1470
Running           1420
Sandals           1387
Lifestyle         1347
Boots             1301
Basketball        1229
Training          1151
Skate             1117
Cross-Training     378
Name: category, dtype: int64

In [22]:
shoe_sales['gender'].value_counts()

#Standardize text formatting
shoe_sales['gender']=shoe_sales['gender'].str.title()
shoe_sales['gender'].value_counts()

women_mapping={"Women":"Womens","W":"Womens"}
shoe_sales['gender'].map(women_mapping)
shoe_sales['gender'].value_counts()

Unisex     2631
Kids       1607
Mens       1120
Womens     1067
Women       608
Youth       590
Child       561
Men         558
Men'S       524
W           518
M           514
Women'S     502
Name: gender, dtype: int64

In [9]:
#Clean shoe size column by removing text characters and trailing whitespaces
shoe_sales['size'].value_counts()

shoe_sales['size']=shoe_sales['size'].str.strip('US')
shoe_sales['size'].value_counts()

shoe_sales['size']=shoe_sales['size'].str.strip('ize')
shoe_sales['size'].value_counts()

shoe_sales['size']=shoe_sales['size'].str.strip('.0')
shoe_sales['size'].value_counts()

shoe_sales['size']=shoe_sales['size'].str.strip()
shoe_sales['size'].value_counts()

11      910
8.5     904
9.5     893
8       882
7       867
9       853
12      852
7.5     851
10.5    848
13      828
6       814
1       722
10      143
Name: size, dtype: int64

In [24]:
#Clean order_status column to ensure consistent text formatting
shoe_sales['order_status'].value_counts()

shoe_sales['order_status']=shoe_sales['order_status'].str.title()
shoe_sales['order_status'].value_counts()

shoe_sales['order_status']=shoe_sales['order_status'].replace({'Complete':'Completed','Return':'Returned','Exchange':'Exchanged','Canceled':'Cancelled'})
shoe_sales['order_status'].value_counts()

Completed    9985
Cancelled     289
Exchanged     275
Returned      251
Name: order_status, dtype: int64

In [28]:
#Standardize formatting across sales channel column
shoe_sales['channel'].value_counts()

shoe_sales['channel']=shoe_sales['channel'].replace({'In Sto':'In-Store','Insto':'In-Store','In-Sto':'In-Store'})
shoe_sales['channel'].value_counts()

shoe_sales['channel']=shoe_sales['channel'].str.title()
shoe_sales['channel'].value_counts()

shoe_sales['channel']=shoe_sales['channel'].replace({'Phone Order':'Phone','In Store':'In-Store','Instore':'In-Store','Web':'Online'})
shoe_sales['channel'].value_counts()

In-Store    3624
Online      3610
Phone       3566
Name: channel, dtype: int64

In [29]:
#Ensure consistent formatting for payment method column
shoe_sales['payment_method'].value_counts()

shoe_sales['payment_method']=shoe_sales['payment_method'].str.title()
shoe_sales['payment_method'].value_counts()

shoe_sales['payment_method']=shoe_sales['payment_method'].replace({'Paypal':'PayPal','Debit':'Debit Card','Applepay':'Apple Pay','Cc':'Credit Card','Gc':'Gift Card','Credit':'Credit Card','Pay Pal':'PayPal','Gift-Card':'Gift Card'})
shoe_sales['payment_method'].value_counts()

Cash           1930
Apple Pay      1821
PayPal         1796
Credit Card    1781
Gift Card      1775
Debit Card     1697
Name: payment_method, dtype: int64

In [31]:
#Clean unit price column to ensure all decimal values with no $ attached 
shoe_sales['unit_price']=shoe_sales['unit_price'].str.replace('$','')
shoe_sales['unit_price'].value_counts()

shoe_sales['unit_price']=shoe_sales['unit_price'].str.replace('-','')
shoe_sales['unit_price'].value_counts().head(50)

92.42     70
68.32     68
150.81    67
188.19    65
174.23    61
161.09    56
196.52    55
154.82    49
167.40    44
47.93     43
139.71    42
131.59    42
105.39    42
122.73    41
111.35    41
48.14     41
216.54    41
194.20    41
196.50    40
171.32    40
101.32    40
95.60     40
89.12     39
150.66    39
189.49    39
139.81    39
119.75    39
84.04     39
91.49     38
157.19    38
174.43    38
69.14     38
93.31     38
158.58    37
159.06    37
176.79    37
42.50     37
81.78     37
150.59    37
91.14     37
210.92    37
55.40     36
129.15    36
219.97    36
91.63     36
61.84     36
76.71     36
90.20     36
204.43    36
145.71    36
Name: unit_price, dtype: int64

In [32]:
#Ensure all quantity values are positive integers, no negative values
shoe_sales['quantity'].value_counts()

shoe_sales['quantity']=shoe_sales['quantity'].replace(-1,1)
shoe_sales['quantity'].value_counts()

1     5389
2     2670
3     1367
4     1308
25      37
0       29
Name: quantity, dtype: int64

In [33]:
#Remove % sign for discount column
shoe_sales['discount_pct'].value_counts()

shoe_sales['discount_pct']=shoe_sales['discount_pct'].str.strip('%')
shoe_sales['discount_pct'].value_counts()

0       4028
0.3      741
30       703
15       683
25       682
0.1      680
0.15     678
0.25     660
20       642
0.2      640
10       623
Name: discount_pct, dtype: int64

In [ ]:
shoe_sales

In [35]:
#Find and remove duplicate values for Transaction ID
duplicates=shoe_sales.duplicated(subset='transaction_id')
shoe_sales[duplicates].sort_values(by='transaction_id')
shoe_sales.drop_duplicates().head(50)

,transaction_id,order_datetime,store_id,customer_id,customer_name,customer_email,customer_phone,customer_state,product_id,product_name,...,category,gender,color,size,quantity,unit_price,discount_pct,payment_method,order_status,channel
0,TXN104355,2024-10-09,ST032,C44543,Mr. Larry Mcclure PhD,mr..larry.mcclure.phd@outlook.com,NaN,CA,P0048,Skechers Basketball Retro 4,...,Basketball,Child,NaN,11,1,131.27,25,Debit Card,Completed,In-Store
1,TXN102187,2024-12-10,ST013,C26663,Sara Gordon,sara.gordon@aol.com,029-254-6862,MN,P0063,Adidas Casual Classic Leather,...,Casual,Unisex,Blue,8,1,164.90,0.3,Debit Card,Completed,In-Store
2,TXN103649,2025-11-17,ST008,C39850,Jessica Simmons,jessica.simmons@gmail.com,955.356.0331,GA,P0247,ASICS Lifestyle Disruptor II,...,Lifestyle,Men'S,Brown,11,4,143.30,15,Gift Card,Completed,Phone
3,TXN104559,2023-06-20,ST009,C24533,Sean Lewis,sean.lewis@hotmail.com,2151734660,NaN,P0215,Skechers Sandals Chuck 70,...,Sandals,Unisex,Black,8,2,105.56,0.1,Cash,Completed,In-Store
4,TXN103935,2025-01-07,ST013,C11482,Carrie Fernandez,carrie.fernandez@gmail.com,+14760882309,Georgia,P0283,Reebok SK8-Hi,...,Lifestyle,Unisex,Black/White,7,2,167.56,0,Debit Card,Completed,In-Store
5,TXN101690,2024-03-23,ST018,C28101,Danielle Cook,danielle.cook@gmail.com,NaN,TN,P0299,Adidas Stan Smith Lifestyle,...,Lifestyle,Unisex,Multicolor,13,1,58.09,0.25,Credit Card,Completed,Online
6,TXN103592,2024-01-15,ST011,C85941,Lance Harris,lance.harris@gmail.com,(870) 929-5162,TN,P0293,Puma Lifestyle 574,...,Lifestyle,Kids,Brown,13,1,140.88,0,PayPal,Completed,Phone
7,TXN107022,2025-05-02,ST023,C52016,Dustin Mitchell,dustin.mitchell@yahoo.com,(579) 672-4610,co,P0242,Converse D'Lites,...,Skate,Unisex,Brown,8,1,69.99,0,Credit Card,Completed,Online
8,TXN109011,2024-08-11,ST016,C14586,Thomas Atkins,thomas.atkins@hotmail.com,628-222-5018,NJ,P0167,Fila RS-X,...,Skate,Men,Brown,6,4,50.94,0,Debit Card,Completed,Phone
9,TXN103765,NaT,ST012,C52813,Samantha Hernandez MD,samantha.hernandez.md@hotmail.com,(511) 788-2805,FL,P0214,New Balance Boots Curry Flow,...,Boots,W,Red,7.5,1,72.54,0,Gift Card,Completed,Online
10,TXN102404,2024-05-25,ST012,C89477,Natalie Hoffman,natalie.hoffman@outlook.com,6665800439,WA,P0081,Vans Sandals Disruptor II,...,Sandals,Womens,Multicolor,9.5,3,118.38,0,Gift Card,Completed,In-Store
11,TXN107574,2025-04-05,ST034,C77357,Rita Waller,rita.waller@gmail.com,(103) 930-8705,PA,P0130,New Balance Sandals 990v5,...,Sandals,Child,Beige,11,3,100.93,0.25,Credit Card,Completed,Online
12,TXN100777,2023-02-19,ST028,C52027,Kayla Bennett,kayla.bennett@yahoo.com,NaN,NJ,P0108,Under Armour Club C,...,Sandals,Men,Brown,8.5,1,147.64,15,Gift Card,Completed,Online
13,TXN110696,2023-03-23,ST007,C75226,Susan Williams,susan.williams@hotmail.com,6740718533,NaN,P0156,Vans Lifestyle Zoom Pegasus,...,Lifestyle,Unisex,Triple Black,9,4,145.71,0,Cash,Completed,Online
14,TXN101177,2025-09-23,ST023,C57734,Joseph Waters,joseph.waters@hotmail.com,1752047700,CA,P0104,Reebok Sandals D'Lites,...,Sandals,Women'S,White,12,1,206.29,0,Apple Pay,Completed,Phone
15,TXN102429,2025-10-23,ST034,C55026,Katherine Olson,NaN,660.323.7014,NaN,P0193,ASICS Basketball Disruptor II,...,Basketball,Men,Green,10.5,1,83.79,0,Debit Card,Completed,Phone
16,TXN101530,2025-09-13,ST022,C15060,Alexis Barker,alexis.barker@hotmail.com,+14916093659,NY,P0283,Reebok SK8-Hi,...,Lifestyle,Unisex,Black/White,10.5,1,167.56,10,Apple Pay,Completed,Online
17,TXN107018,2023-09-19,ST003,C89195,Jason Munoz,jason.munoz@aol.com,0411678815,WA,P0032,Puma Retro 4,...,Cross-Training,Child,Triple Black,11,1,130.96,10,Cash,Completed,In-Store
18,TXN110329,2023-04-30,ST012,C78835,Jerry Williams,jerry.williams@hotmail.com,640.703.0880,Tennessee,P0006,Converse D'Lites Training,...,Cross-Training,Womens,Black,13,1,198.03,0.1,Credit Card,Completed,Phone
19,TXN108854,2022-11-24,ST014,C43767,Ashley White,ashley.white@gmail.com,2059438976,PA,P0228,ASICS 990v5 Basketball,...,Basketball,Unisex,Orange,10.5,1,NaN,0.3,Apple Pay,Completed,Phone
20,TXN103500,2022-01-25,ST003,C32792,Steven Gordon,steven.gordon@gmail.com,NaN,MN,P0072,Reebok 990v5,...,Sandals,Men'S,Black,13,4,219.97,0.25,PayPal,Completed,In-Store
21,TXN103046,2024-12-18,ST016,C20698,Edward Cruz,edward.cruz@hotmail.com,5545012221,TX,P0263,Under Armour Casual Chuck 70,...,Casual,Youth,Red,7.5,2,191.65,0.15,Apple Pay,Completed,Online
22,TXN101803,2024-08-27,ST010,C10419,Lisa Lopez,lisa.lopez@outlook.com,4633891562,Georgia,P0155,Reebok 574 Basketball,...,Basketball,Women'S,White,8,1,199.70,0,Debit Card,Completed,In-Store
23,TXN102718,2024-09-12,ST036,C54059,Desiree Fox,desiree.fox@yahoo.com,+14899300519,NY,P0033,Nike 990v5,...,Boots,Kids,Orange,11,2,47.93,0.2,PayPal,Completed,Online
24,TXN106226,2024-11-20,ST034,C62598,William Dickson DDS,william.dickson.dds@aol.com,3891918740,Florida,P0236,Nike Running Old Skool,...,Running,Kids,Navy,8.5,3,132.76,0,Apple Pay,Completed,Online
25,TXN110682,2023-03-26,ST014,C82973,Julia Jones,julia.jones@aol.com,(809) 010-1461,IL,P0290,ASICS Boots RS-X,...,Boots,Womens,Navy,12,2,122.73,20,Gift Card,Completed,Phone
26,TXN104325,2024-08-21,ST003,C29686,Brian Payne,NaN,791-944-5576,TX,P0188,Reebok D'Lites,...,Lifestyle,Mens,White,8,2,129.52,0,Gift Card,Completed,Online
27,TXN103406,2024-07-02,ST024,C17985,Angela Caldwell,angela.caldwell@hotmail.com,(200) 761-5042,GA,P0225,Fila Classic Leather Sandals,...,Sandals,Mens,Brown,1,4,203.04,0.2,Gift Card,Completed,In-Store
28,TXN110082,2023-09-12,ST006,C27705,Kenneth Huff,kenneth.huff at hotmail.com,405.391.0371,NY,P0205,Nike Gel-Kayano,...,Sandals,Women,Brown,7,4,105.49,0.1,Debit Card,Completed,In-Store
29,TXN103145,2023-04-23,ST015,C10143,Terri Valdez,terri.valdez@gmail.com,+14441076926,NY,P0349,Fila Sandals 574,...,Sandals,Kids,Red,11,1,70.46,0,Cash,Completed,Phone
30,TXN100982,2022-11-05,ST004,C28596,Rebekah Ramirez,rebekah.ramirez@aol.com,(843) 965-6887,MN,P0208,Jordan Curry Flow Casual,...,Casual,M,Navy,10.5,2,144.88,15,Credit Card,Completed,In-Store
31,TXN104401,2024-11-06,ST002,C35969,Krista Crane,krista.crane@aol.com,NaN,ca,P0240,Converse RS-X Skate,...,Skate,M,Beige,1,4,170.86,30,PayPal,Completed,Online
32,TXN100506,2023-02-10,ST025,C60710,Leonard Morales,NaN,NaN,PA,P0196,Converse Disruptor II Casual,...,Casual,Mens,Blue,8,3,66.35,0,Gift Card,Completed,Online
33,TXN101836,2024-05-24,ST030,C26947,Steven Underwood,steven.underwood@yahoo.com,252-423-5256,MI,P0269,Converse RS-X,...,Basketball,W,Navy,9,3,123.96,25,Apple Pay,Completed,Phone
34,TXN104467,2022-03-04,ST023,C85891,Jessica Jones,jessica.jones@outlook.com,(443) 053-4475,MN,P0286,ASICS Boots Chuck 70,...,Boots,Women,Red,9,1,45.67,0.3,Cash,Completed,Phone
35,TXN103734,2024-12-04,ST019,C37149,Stephanie Bender,NaN,516-994-9708,GA,P0227,Puma Basketball D'Lites,...,Basketball,Womens,Black,6,3,115.56,0,Apple Pay,Completed,Online
36,TXN109576,2025-09-18,ST005,C63559,Kurt Vasquez,kurt.vasquez at yahoo.com,087.106.2359,PA,P0176,Converse Running Stan Smith,...,Running,Kids,Grey,7,1,103.29,0,Credit Card,Completed,In-Store
37,TXN108279,2025-12-30,ST036,C36484,Tammy Estrada,tammy.estrada@yahoo.com,(162) 585-1502,ma,P0138,Reebok Zoom Pegasus,...,Skate,Mens,Triple Black,11,2,201.79,0,Gift Card,Completed,Phone
38,TXN101536,2023-10-05,ST001,C23809,Nicholas Shaw,NaN,NaN,tx,P0297,Reebok Skate Club C,...,Skate,Men'S,Red,9.5,1,150.81,0,Credit Card,Completed,In-Store
39,TXN109373,2023-05-18,ST022,C11785,Laura Rodriguez,laura.rodriguez@gmail.com,(910) 292-9501,TN,P0004,Under Armour Cloudfoam Skate,...,Skate,W,Orange,8,1,67.50,20,Gift Card,Completed,Online
40,TXN100145,2025-12-04,ST013,C20357,Daniel Bright,daniel.bright@outlook.com,226.916.6978,PA,P0058,Adidas Casual Zoom Pegasus,...,Casual,Unisex,Beige,12,1,160.15,30,Cash,Completed,In-Store
41,TXN105947,2023-04-28,ST021,C70806,Crystal Montoya,crystal.montoya@outlook.com,(300) 716-9500,NaN,P0297,Reebok Skate Club C,...,Skate,Men,Red,7.5,1,150.81,10,Debit Card,Completed,Phone
42,TXN104600,2023-11-21,ST006,C44253,Sara Castro,sara.castro@yahoo.com,652-057-5639,NY,P0108,Under Armour Club C,...,Sandals,Men'S,Brown,8.5,1,147.64,0.25,Gift Card,Completed,Phone
43,TXN107547,2025-02-20,ST035,C94823,Micheal Perry,micheal.perry@yahoo.com,NaN,NJ,P0090,Under Armour Retro 4,...,Lifestyle,Unisex,Multicolor,9.5,1,88.75,0.3,Debit Card,Completed,In-Store
44,TXN107356,2022-07-31,ST006,C82867,Tommy Potter,tommy.potter@outlook.com,9854506935,TX,P0060,ASICS Sandals Chuck 70,...,Sandals,Child,Brown,7,1,NaN,0.1,Cash,Completed,Phone
45,TXN108563,2024-05-22,ST020,C11770,Emily Palmer,NaN,(132) 796-8559,TX,P0129,Adidas Sandals RS-X,...,Sandals,Womens,Black,8.5,2,113.79,0,Apple Pay,Completed,Online
46,TXN110469,2022-08-15,ST028,C75143,Nicole Robinson,nicole.robinson@yahoo.com,(202) 204-1064,pa,P0233,Converse Gel-Kayano,...,Basketball,Kids,Beige,8,2,64.00,0,Cash,Completed,Online
47,TXN100056,2025-11-10,ST032,C20271,Jennifer Hampton,jennifer.hampton@outlook.com,NaN,NV,P0154,Fila D'Lites Boots,...,Boots,W,White,10.5,1,48.15,15,Apple Pay,Completed,Phone
48,TXN103981,NaT,ST006,C47337,Autumn Harris,autumn.harris@hotmail.com,(725) 978-3367,NJ,P0168,Vans Stan Smith Basketball,...,Basketball,Unisex,Brown,12,2,53.22,0.25,Credit Card,Exchanged,Phone
49,TXN107040,2025-12-12,ST011,C71739,Vanessa Booth,vanessa.booth@hotmail.com,574-865-9775,IL,P0301,Reebok Retro 4 Skate,...,Skate,Mens,Triple Black,7.5,1,203.42,0.25,Gift Card,Completed,In-Store

In [38]:
#Load store info CSV and convert to DataFrame
store_info=pd.read_csv('/Users/aaronless/Desktop/Data Analysis Porfolio Projects/Marketing:Sales/Shoe Sales/Original CSVs/stores_1.csv')
store_info

,store_id,store_name,city,state,region,store_type,open_date,square_footage
0,ST001,StrideZone New York Mall,New York,NY,Northeast,Mall,2020-07-16,9500
1,ST002,StrideZone New York Center,New York,NY,Northeast,Outlet,2011-12-09,3200
2,ST003,StrideZone New York Plaza,New York,NY,Northeast,Mall,2015-06-10,9500
3,ST004,StrideZone Boston Square,Boston,MA,NaN,Mall,2014-09-18,7000
4,ST005,StrideZone Boston Commons,Boston,MA,Northeast,Mall,2021-11-24,2500
5,ST006,StrideZone Boston Mall,Boston,MA,Northeast,Outlet,2021-01-22,3200
6,ST007,StrideZone Philadelphia Square,Philadelphia,PA,Northeast,Mall,2024-01-29,7000
7,ST008,StrideZone Philadelphia Plaza,Philadelphia,PA,Northeast,Strip Mall,2012-10-21,3200
8,ST009,StrideZone Philadelphia Commons,Philadelphia,PA,Northeast,Flagship,2017-06-30,2500
9,ST010,StrideZone Newark Commons,Newark,NJ,Northeast,Flagship,2012-01-03,4000
10,ST011,StrideZone Chicago Plaza,Chicago,il,Midwest,Flagship,2014-08-25,2500
11,ST012,StrideZone Detroit Commons,Detroit,MI,Midwest,Mall,2018-08-30,4000
12,ST013,StrideZone Columbus Square,Columbus,OH,Midwest,Flagship,2011-12-17,2500
13,ST014,StrideZone Columbus Commons,Columbus,OH,Midwest,Mall,2014-05-16,5500
14,ST015,StrideZone Minneapolis Square,Minneapolis,MN,Midwest,Flagship,2020-09-07,9500
15,ST016,StrideZone Atlanta Center,Atlanta,GA,South,Outlet,2019-03-21,9500
16,ST017,StrideZone Atlanta Mall,Atlanta,GA,South,Mall,2014-09-04,9500
17,ST018,StrideZone Atlanta Plaza,Atlanta,GA,South,Flagship,2019-11-02,2500
18,ST019,StrideZone Houston Mall,Houston,TX,South,Strip Mall,2022-12-02,4000
19,ST020,StrideZone Dallas Center,Dallas,TX,South,Outlet,2011-09-06,4000
20,ST021,StrideZone Dallas Center,Dallas,TX,South,Outlet,2022-11-14,9500
21,ST022,StrideZone Miami Mall,Miami,FL,South,Outlet,2021-05-12,7000
22,ST023,StrideZone Miami Plaza,Miami,FL,South,Outlet,2016-05-08,5500
23,ST024,StrideZone Charlotte Center,Charlotte,NC,South,Outlet,2013-10-06,9500
24,ST025,StrideZone Charlotte Center,Charlotte,NC,South,Mall,2024-12-27,3200
25,ST026,StrideZone Nashville Center,Nashville,TN,South,Strip Mall,2016-04-20,4000
26,ST027,StrideZone Los Angeles Plaza,Los Angeles,CA,West,Flagship,2012-11-20,3200
27,ST028,StrideZone San Francisco Commons,San Francisco,CA,West,Strip Mall,2012-12-10,9500
28,ST029,StrideZone San Francisco Commons,San Francisco,CA,West,Outlet,2023-06-15,4000
29,ST030,StrideZone San Francisco Plaza,San Francisco,CA,West,Outlet,2020-01-15,9500
30,ST031,StrideZone Seattle Square,Seattle,WA,West,Flagship,2022-11-20,9500
31,ST032,StrideZone Seattle Square,Seattle,WA,West,Strip Mall,2021-10-21,7000
32,ST033,StrideZone Seattle Commons,Seattle,WA,West,Flagship,2019-02-04,3200
33,ST034,StrideZone Denver Square,Denver,CO,West,Strip Mall,2025-03-18,2500
34,ST035,StrideZone Phoenix Mall,Phoenix,AZ,West,Outlet,2016-11-20,9500
35,ST036,StrideZone Las Vegas Commons,Las Vegas,NV,West,Mall,2019-04-26,5500

In [52]:
#Ensure all state abbreviations are uppercase
store_info['state']=store_info['state'].str.upper()
store_info

#Fill in missing region value
store_info['region']=store_info['region'].fillna('Northeast')
store_info

,store_id,store_name,city,state,region,store_type,open_date,square_footage
0,ST001,StrideZone New York Mall,New York,NY,Northeast,Mall,2020-07-16,9500
1,ST002,StrideZone New York Center,New York,NY,Northeast,Outlet,2011-12-09,3200
2,ST003,StrideZone New York Plaza,New York,NY,Northeast,Mall,2015-06-10,9500
3,ST004,StrideZone Boston Square,Boston,MA,Northeast,Mall,2014-09-18,7000
4,ST005,StrideZone Boston Commons,Boston,MA,Northeast,Mall,2021-11-24,2500
5,ST006,StrideZone Boston Mall,Boston,MA,Northeast,Outlet,2021-01-22,3200
6,ST007,StrideZone Philadelphia Square,Philadelphia,PA,Northeast,Mall,2024-01-29,7000
7,ST008,StrideZone Philadelphia Plaza,Philadelphia,PA,Northeast,Strip Mall,2012-10-21,3200
8,ST009,StrideZone Philadelphia Commons,Philadelphia,PA,Northeast,Flagship,2017-06-30,2500
9,ST010,StrideZone Newark Commons,Newark,NJ,Northeast,Flagship,2012-01-03,4000
10,ST011,StrideZone Chicago Plaza,Chicago,IL,Midwest,Flagship,2014-08-25,2500
11,ST012,StrideZone Detroit Commons,Detroit,MI,Midwest,Mall,2018-08-30,4000
12,ST013,StrideZone Columbus Square,Columbus,OH,Midwest,Flagship,2011-12-17,2500
13,ST014,StrideZone Columbus Commons,Columbus,OH,Midwest,Mall,2014-05-16,5500
14,ST015,StrideZone Minneapolis Square,Minneapolis,MN,Midwest,Flagship,2020-09-07,9500
15,ST016,StrideZone Atlanta Center,Atlanta,GA,South,Outlet,2019-03-21,9500
16,ST017,StrideZone Atlanta Mall,Atlanta,GA,South,Mall,2014-09-04,9500
17,ST018,StrideZone Atlanta Plaza,Atlanta,GA,South,Flagship,2019-11-02,2500
18,ST019,StrideZone Houston Mall,Houston,TX,South,Strip Mall,2022-12-02,4000
19,ST020,StrideZone Dallas Center,Dallas,TX,South,Outlet,2011-09-06,4000
20,ST021,StrideZone Dallas Center,Dallas,TX,South,Outlet,2022-11-14,9500
21,ST022,StrideZone Miami Mall,Miami,FL,South,Outlet,2021-05-12,7000
22,ST023,StrideZone Miami Plaza,Miami,FL,South,Outlet,2016-05-08,5500
23,ST024,StrideZone Charlotte Center,Charlotte,NC,South,Outlet,2013-10-06,9500
24,ST025,StrideZone Charlotte Center,Charlotte,NC,South,Mall,2024-12-27,3200
25,ST026,StrideZone Nashville Center,Nashville,TN,South,Strip Mall,2016-04-20,4000
26,ST027,StrideZone Los Angeles Plaza,Los Angeles,CA,West,Flagship,2012-11-20,3200
27,ST028,StrideZone San Francisco Commons,San Francisco,CA,West,Strip Mall,2012-12-10,9500
28,ST029,StrideZone San Francisco Commons,San Francisco,CA,West,Outlet,2023-06-15,4000
29,ST030,StrideZone San Francisco Plaza,San Francisco,CA,West,Outlet,2020-01-15,9500
30,ST031,StrideZone Seattle Square,Seattle,WA,West,Flagship,2022-11-20,9500
31,ST032,StrideZone Seattle Square,Seattle,WA,West,Strip Mall,2021-10-21,7000
32,ST033,StrideZone Seattle Commons,Seattle,WA,West,Flagship,2019-02-04,3200
33,ST034,StrideZone Denver Square,Denver,CO,West,Strip Mall,2025-03-18,2500
34,ST035,StrideZone Phoenix Mall,Phoenix,AZ,West,Outlet,2016-11-20,9500
35,ST036,StrideZone Las Vegas Commons,Las Vegas,NV,West,Mall,2019-04-26,5500

In [51]:
#Remove irrelevant columns
shoe_sales=shoe_sales.drop(columns=['customer_name','customer_email','customer_phone'])

KeyError: "['customer_name' 'customer_email' 'customer_phone'] not found in axis"

In [47]:
#Ensure consistency across shoe brand column
shoe_sales['brand'].value_counts()

shoe_sales['brand']=shoe_sales['brand'].str.title()
shoe_sales['brand'].value_counts()

shoe_sales['brand']=shoe_sales['brand'].replace({'Ua':'Under Armour','N.Balance':'New Balance'})
shoe_sales['brand'].value_counts()

shoe_sales['brand']=shoe_sales['brand'].replace({'Asics':'ASICS','Fila':'FILA'})
shoe_sales['brand'].value_counts()

Reebok          1283
ASICS           1079
Converse        1063
Under Armour     946
Vans             926
Puma             917
FILA             884
Adidas           859
New Balance      756
Skechers         746
Jordan           696
Nike             645
Name: brand, dtype: int64

In [48]:
#Check for insconsistencies in the color column
shoe_sales['color'].value_counts()

Triple Black    1126
Brown           1034
Orange           911
Multicolor       814
White            762
Black/White      757
Beige            730
Navy             699
Green            691
Black            665
Blue             641
White/Red        590
Grey             562
Red              513
Name: color, dtype: int64